### ISSUE TITLE
我想问问liigo说的那些被修复的有多少? liigo的客观性有多少?

### ISSUE THREAD

**Issue by hhniao** [xmge/gonote#12]
看了[@liigo](https://github.com/liigo) 的博客. 他说了很多关于go缺点. 有一些我认为说的很好, 有一些是可有可无的. 
但是新手一枚, 有一些还是不能体会到其中的精髓.
请大神说一下.

**Comment by xmge** [comment]
我从java转go，单说这两种，如果再让我写个项目，我会选go。
理由：java很繁琐，go很直接
---
用其他语言和go从头写个小项目就知道了

**Comment by xmge** [comment]
https://www.sohu.com/a/121469368_374240

**Comment by hhniao** [comment]
额, 首先感谢你回复.
文不对题, go的优点, 我知道. 我也用go写了一个练手项目, 目前还没有写完. 很容易上手.
我问的是liigo说的那些缺点.

**Comment by hhniao** [comment]
比如, 他说到go国内活跃, 但是国外不活跃. 是否属实. 有权威数据来源吗?
[golang缺点](https://github.com/xmge/gonote/blob/master/golang%E4%B8%93%E9%A2%98%E8%AE%B2%E8%A7%A3/golang%E7%BC%BA%E7%82%B9.md)
他说的这些, 垃圾回收机制, 错误处理机制.

**Comment by xmge** [comment]
很抱歉，暂时无法回答这些疑问，因为没有做过调研，将来会写一篇解答此问题的文章。
