### ISSUE TITLE
golang面试题的卷一的参考答案第三题标题写成第二题了

### ISSUE THREAD

**Issue by KiripengTsai** [xmge/gonote#7]

**Comment by xmge** [comment]
好的，谢谢，已经做了修改。早点休息哦😊

**Comment by xmge** [comment]
有时间的话可以共同完成里面的题目，能有不少提高的☺

**Comment by KiripengTsai** [comment]
type People struct{}

func (p *People) ShowA() {
	fmt.Println("showA")
	p.ShowB()
}
func (p *People) ShowB() {
	fmt.Println("showB")
}

type Human struct{}

func (h *Human) ShowA() {
	fmt.Println("Human showA")
}

type Teacher struct {
	People
}

func (t *Teacher) ShowB() {
	fmt.Println("teacher showB")
}

func main() {
	t := Teacher{}
	t.ShowA()
}
还有这个在1.11版本运行没出错来着//
result：
showA
showB
