### ISSUE TITLE
第一题答案

### ISSUE THREAD

**Issue by Ouroboros** [xmge/gonote#9]
解析：
```
 “触发异常”可能出现在任何位置。
  defer是先进后出，逆序执行。
  panic()函数相当与go出去的一个协程
```

这是认真的?

https://blog.golang.org/defer-panic-and-recover

**Comment by xmge** [comment]
很抱歉，我主观臆断了。卷一还没有写完，有的东西只是当时想法，先写上去，并没有去考证。谢谢你给出答案

**Comment by xmge** [comment]
已经做了相应的修改，等晚上重新写答案，谢谢了😀
